In [188]:
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__

'2.14.0'

In [189]:
dataset = pd.read_csv('./Churn_Modelling.csv')
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [190]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])


In [191]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [192]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)
print(X_train)
print(y_train)
print(X_train.dtype, y_train.dtype)
X_train = X_train.astype('float32')



[[0.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 0.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 0.0 ... 1 0 181429.87]
 [0.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]
[0 0 0 ... 0 0 1]
object int64


In [193]:
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)
# print(X_train)


In [194]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100


250/250 [==============================] - 1s 2ms/step - loss: 824.5922 - accuracy: 0.6134
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 28.2049 - accuracy: 0.6736
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 23.7209 - accuracy: 0.6775
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 20.0261 - accuracy: 0.6744
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 21.7300 - accuracy: 0.6755
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 15.8714 - accuracy: 0.6789
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 16.6621 - accuracy: 0.6796
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 15.9151 - accuracy: 0.6794
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 21.8460 - accuracy: 0.6786
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 19.9500 - accurac

In [195]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)


In [196]:

X_test = X_test.astype('float32')
print(X_test.dtype)
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


float32


63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [197]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1589    6]
 [ 397    8]]


0.7985